[package]
name = "modrinth_modpack_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
home = "0.5.11"
json = "0.12.4"
reqwest = { version = "0.12.15", features = ["blocking"] }
sha2 = "0.10.8"
zip = "2.6.1"
